services:
- postgresql
addons:
  postgresql: '9.5'
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database test_db;' -U postgres
language: ruby
rvm:
- 2.5.5
script:
- bundle install --jobs=3 --retry=3
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
<<<<<<< Updated upstream
    secure: soh0mGPEiiFiwGEdIQzzkijJzewDTy1B0tOxYGlTaaKD/I5SriFNJtQXhC9CJOjoJpbNhgBwnXkebsR7nXZ53i+tkxgWEZAOVjuhwJEkMJkrrf3x/9hLUjzE3Guo29enmG60GLziAGjBvk0znmYAvJHVSRzo21Qnnhx56odWxy0LTDqgN/5wVjEy/jCtkQrXSnpwzc6smxVHg+QS6fysCceIwuSXrrRHn5brCJhoRi/1kXIEYNbYrbxukg+PpHjPugtRz23fWppbDj/DKc/iqFxhvzF9ns7Ym3/JXrJG5Mmei/4xCt8xEfefIKgVzQCGS2OXM+3/ThQw5vckKc/0JuVv2kYY+QGydW7z7OYeoD2BqHUkZHVphiuUsULOCKwsuMF+EMmgU9NvB6T1uCCQ4Wz/KQf6HSR4JxG2vvWnAl9A+EvlSaJc/vjksHCBhwzarF+BBGQ5uQ+QVIXiCh22WHgJLju/LKBr8X0KfKHV0YTL1ROPxKnVYd6P6/G2tgeCHK5QwuWeNM/xscxxoDkn/4xehZDLMkCkuk3e1H47kAUU7cvDKB/dDh8vp2ul+ZHENzCWOJWq+Esf6jmwlKByo+CsdEo2QnvdEvlRFVxEMB9aTxPT9b40vAQZs1dRXv+H+mJALnV0Ymmt98db8S0jHH8KC9YFP3aMmkfuiXD6yR8=
=======
    secure: irP3dhfFvF5EOpoF+0s+liMjO6lT7GPs1JDKLxI/PrnrtNRknXmTTeSRNofw05vYaVHOzSrpu5aUsajwMFBSC8NDkgcKRTqqQ+a5lb5ye32rjYG50rXX4wtuVC4pPNM6nYDc0rHhZfaVUQZkhjCuvNq9SklHqGItWXZFZ0DcEUPLBpM0wh3zl6agEAsDR613S4EWcPs+mTKD1GR1RIP7CNvMywS02T29v7/osT+Ml/NtYWA7dSoWKzHB1ouaVsEdq+m+Og5TZx2ojstmIlcD/vkMbiFAzss2VUKOte8zz+ruLvcF1ERVbt/CSbxmLz8SBHrGFk7QNGk8CAaLJI4WEqN3x68GQm2CgEV7csb4JavO+x6WGD3nRwf1ZOXNJpc8138shB1ZJ9nZO9y/mTQKONhVI7Bi9z6S3OsoEkS1xCQF1WLel44DrTO6n1E07z6U/Nn5hnopa6y5s9YrAEWglBllSwWfEKGATx2gQbaeb6i1WkkJ65db04FgaLUd9w8927Dcmu3mUvpxm4bujkLlga0FUIF76qoS68KHnxGgwe/+Wl50xWxxmUJ36McZiRi4lE3IILWAQni5yK0UNBH2AKXp3Xw7g8mckpjU9Wke3DWDNsqxnbrQZUzS7c6nXXqMUjQ0NdtsiG6hqsspib3Tyaq9iTl6r3gwqp1JcqPPzls=
>>>>>>> Stashed changes
  app:
    stable: lifetoremindhub
    master: lifetoremindhubdevel
  on:
    repo: eduqg/LifeToRemind
