services:
- postgresql
addons:
  postgresql: '9.5'
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database test_db;' -U postgres
language: ruby
rvm:
- 2.5.5
script:
- bundle install --jobs=3 --retry=3
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: WD2eQXmwxB+VFYaRqumfI57RvHPAIc9r+LR244T6CUuC5SQhcJivCITsABLbNVhYpAjKY/zCkhSA/Nu6oBWTMV0WGnhbZfGGKxkwYqbzBGX1TfwLBI1vocUzpa3dOvsiACsZ8YGeyZPaxooTpIlWsul/l6SjmgItzw51JeR/zxeXRQCrH+kkS67t6wMl2nK9LInJyqkyvYREK4Vz2ZTIGB9xvMxljIb3G++DTMstJawndFFwoE1yMEfU6JRcQUqsmkJS0CTQs79z0IslXWEY88orrU/qbvgWyq3zxdRWdZ6cQ/VEs7O/GbdD9jHSoqVYlNWexH9DRFrctMFY3meysxQ1MOm7HiFNY+oB9wWDUzmVuqGgnuG2yCqeYDISVd525Q00mRxueMBA48wzJYqPI9nlXHTtX74LopbYYCpIcdkZ5RCgaUJdRWprtTyP/vvyj4Noevn8cMsAipLJpabCZ/MWZdx4HoQlL7Mh3Dd90VnjYUkNsJPzcfs2YjwmiGT9RW7mRVvwxAEIkHSxGjxXzH6M/zHb0+pcTxfvc5y2bRBR6Oy4TBSC0tsahnxXilguPX4ZODRdbFBk0zpWhIoMO9rHMnTHU3Xmc1JhMbHrCF74npJyGkgRlLHS0Ovw/HD7dculXuIBuLKViWvAp7Vo3Kf4j5SlI6gdHGdcuAOcYI0=
  app:
    stable: lifetoremindhub
    master: lifetoremindhubdevel
  on:
    repo: eduqg/LifeToRemind
